export type SimulationMetricName =
  | "repositionUnits"
  | "assignment.rebuild"
  | "assignment.defense"
  | "assignment.attack"
  | "movement.progression"
  | "pathfinding.bfs"
  | "landFront.rebuild"
  | "landFront.metrics"
  | "landFront.planEvaluation"
  | "landFront.allocation"
  | "offensiveOperation.evaluation"
  | "offensiveOperation.targetAssignment"
  | "retreat.evaluation"
  | "retreat.targetAssignment"
  | "capitalDefense.evaluation"
  | "updateOccupation"
  | "updateCapitals"
  | "surrender";

export type SimulationCounterName =
  | "pathfinding.bfs"
  | "pathfinding.bfsFound"
  | "pathfinding.bfsUnreachable"
  | "pathfinding.exploredRegions"
  | "pathfinding.shared.requests"
  | "pathfinding.shared.hits"
  | "pathfinding.shared.misses"
  | "pathfinding.shared.fieldsCreated"
  | "pathfinding.shared.fieldsDiscarded"
  | "pathfinding.shared.entriesBuilt"
  | "pathfinding.shared.invalidations"
  | "pathfinding.shared.invalidation.map"
  | "pathfinding.shared.invalidation.territory"
  | "pathfinding.shared.invalidation.occupation"
  | "pathfinding.shared.invalidation.building"
  | "pathfinding.shared.invalidation.wars"
  | "target.reassignments"
  | "movement.regionArrivals"
  | "occupation.fullRegionScans"
  | "occupation.regionsScanned"
  | "capitals.activeNationScans"
  | "world.occupationChanges"
  | "world.territoryChanges"
  | "landFront.rebuilds"
  | "landFront.metricRefreshes"
  | "landFront.frontsBuilt"
  | "landFront.planUpdates"
  | "landFront.plansEvaluated"
  | "landFront.allocationRebuilds"
  | "landFront.allocationUnitSwitches"
  | "landFront.allocationFrontTransfers"
  | "landFront.allocationUnassignedUnits"
  | "offensiveOperation.created"
  | "offensiveOperation.completed"
  | "offensiveOperation.failed"
  | "offensiveOperation.cancelled"
  | "offensiveOperation.phaseTransitions"
  | "offensiveOperation.unitAssignments"
  | "offensiveOperation.targetAssignments"
  | "offensiveOperation.unitTargetSwitches"
  | "offensiveOperation.preparingTicks"
  | "offensiveOperation.attackingTicks"
  | "offensiveOperation.activeSamples"
  | "offensiveOperation.activeSampleCount"
  | "offensiveOperation.targetChanges"
  | "offensiveOperation.targetConcentrationTotal"
  | "offensiveOperation.targetConcentrationSamples"
  | "offensiveOperation.targetConcentrationMax"
  | "retreat.created"
  | "retreat.completed"
  | "retreat.cancelled"
  | "retreat.phaseTransitions"
  | "retreat.rearguardUnits"
  | "retreat.withdrawingUnits"
  | "retreat.arrivedUnits"
  | "retreat.regroupedToFront"
  | "retreat.returnedToDefense"
  | "retreat.targetAssignments"
  | "retreat.unitTargetSwitches"
  | "capitalDefense.emergencies"
  | "capitalDefense.criticalEmergencies"
  | "capitalDefense.emergencyDurationTicks"
  | "capitalDefense.reallocatedUnits"
  | "capitalDefense.fallbackSelections"
  | "capitalDefense.operationCancellations"
  | "capitalDefense.capitalFalls"
  | "capitalDefense.unguardedTicks";

/**
 * Optional benchmark observer. Production worlds do not install one, so hot paths
 * only pay for an undefined property check and never call performance.now().
 */
export interface SimulationInstrumentation {
  recordDuration(name: SimulationMetricName, durationMs: number): void;
  incrementCounter(name: SimulationCounterName, amount?: number): void;
}
