import type { MicroRegion } from "../worldgen/micro-region";
import type { MicroRegionEdge } from "../worldgen/micro-region-edge";
import type { MacroRegion } from "../worldgen/macro-region";
import type { MesoRegion } from "../worldgen/meso-region";
import type { BattleState } from "./battles";
import type { NationRuntime } from "./nation-runtime";
import type { OccupationState } from "./occupation";
import type { SimTime } from "./time";
import type { UnitState } from "./unit";
import type { WarState } from "./war-state";
import type { SeededRng } from "../utils/seeded-rng";
import type { WorldCache } from "./world-cache";
import type { SimulationInstrumentation } from "./instrumentation";
import type { LandFrontState } from "./land-fronts";
import type { NationFrontPlanState } from "./nation-front-plans";
import type { NationFrontAllocationState } from "./nation-front-allocations";
import type { OffensiveOperationState } from "./offensive-operations";
import type { RetreatPlanState } from "./retreat-plans";
import type { CapitalDefenseState } from "./capital-defense";
import type { StrategicReserveState } from "./strategic-reserves";
import type { ReorganizationState } from "./reorganization";
import type { FrontlineCoverageState } from "./frontline-coverage";
import type { StalematePressureState } from "./stalemate-pressure";
import type { CollapseAdvanceState } from "./collapse-advance";
import type { StrategicProgressState } from "./strategic-progress";
import type { BattlefieldTopologyState } from "./battlefield-topology";
import type { SupplyAssessmentState } from "./supply-assessment";
import type { IsolationEffectsState } from "./isolation-effects";
import type { ProductionDiagnosticsState } from "./production";
import type { SupplyCutoffAnalysisState } from "./supply-cutoff";
import type { SupplyDefenseState } from "./supply-defense";
import type { SupplyReliefState } from "./supply-relief";
import type { AmphibiousOperationState } from "./amphibious";
import type { StrategicThreatObservationState } from "./strategic-threat-observation";

export interface WorldState {
  width: number;
  height: number;
  microRegions: MicroRegion[];
  microRegionEdges: MicroRegionEdge[];
  mesoRegions: MesoRegion[];
  macroRegions: MacroRegion[];
  nations: NationRuntime[];
  wars: WarState[];
  battles: BattleState[];
  occupation: OccupationState;
  landFronts: LandFrontState;
  frontPlans: NationFrontPlanState;
  frontAllocations: NationFrontAllocationState;
  frontlineCoverage: FrontlineCoverageState;
  offensiveOperations: OffensiveOperationState;
  retreatPlans: RetreatPlanState;
  capitalDefense: CapitalDefenseState;
  strategicReserves: StrategicReserveState;
  reorganization: ReorganizationState;
  strategicProgress: StrategicProgressState;
  /** Observation-only strategic measurements. No AI decision consumes this. */
  strategicThreatObservation: StrategicThreatObservationState;
  battlefieldTopology: BattlefieldTopologyState;
  supplyAssessment: SupplyAssessmentState;
  isolationEffects: IsolationEffectsState;
  productionDiagnostics: ProductionDiagnosticsState;
  supplyCutoffs: SupplyCutoffAnalysisState;
  supplyDefense: SupplyDefenseState;
  supplyRelief: SupplyReliefState;
  amphibiousOperations: AmphibiousOperationState;
  stalematePressure: StalematePressureState;
  collapseAdvances: CollapseAdvanceState;
  mapVersion: number;
  territoryVersion: number;
  buildingVersion: number;
  units: UnitState[];
  unitIdCounter: number;
  simRng: SeededRng;
  cache: WorldCache;
  time: SimTime;
  instrumentation?: SimulationInstrumentation;
}
